# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	./etc/bashrc
fi

# Setting ENV from JAVA, HADOOP, SPARK, Share Libary and PATH
export JAVA_HOME=/usr/lib/jvm/java-openjdk

export HADOOP_HOME=/root/hadoop

export HADOOP_CONF_DIR=$HADOOP_HOME/etc/hadoop

export SPARK_HOME=/root/spark

export LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH:$HADOOP_HOME/lib/native/:.

export PATH=.:$PATH:$JAVA_HOME/bin:$HADOOP_HOME/bin:$HADOOP_HOME/sbin:$SPARK_HOME/bin:$SPARK_HOME/sbin

export CLASSPATH=.:$JAVA_HOME/lib/tools.jar:$JAVA_HOME/lib/dt.jar
